
 mpumalanga = SelectField(u'Area', choices=[('Acornhoek', 'Acornhoek'),('Amersfoort', 'Amersfoort'),('Amsterdam', 'Amsterdam'),
('Badplaas', 'Badplaas'),('Balfour', 'Balfour'),('Balmoral', 'Balmoral'),('Bankkop', 'Bankkop'),('Barberton', 'Barberton'),
('Belfast', 'Belfast'),('Berbice', 'Berbice'),('Bethal', 'Bethal'),('Bettiesdam', 'Bettiesdam'),('Bosbokrand', 'Bosbokrand'),
('Breyten', 'Breyten'),('Carolina', 'Carolina'),('Charl Cilliers', 'Charl Cilliers'),('Chrissiesmeer', 'Chrissiesmeer'),
('Clewer', 'Clewer'),('Coalville', 'Coalville'),('Commondale', 'Commondale'),('Cork', 'Cork'),('Delmas', 'Delmas'),
('Dullstroom', 'Dullstroom'),('Ermelo', 'Ermelo'),('Graskop', 'Graskop'),('Greylingstad', 'Greylingstad'),('Hazyview', 'Hazyview'),
('Hectorspruit', 'Hectorspruit'),('Kaapmuiden', 'Kaapmuiden'),('Kinross', 'Kinross'),('Komatipoort', 'Komatipoort'),('Kriel', 'Kriel'),
('KwaMhlanga', 'KwaMhlanga'),('Loopspruit', 'Loopspruit'),('Lydenburg', 'Lydenburg'),('Machadodorp', 'Machadodorp'),('Malelane', 'Malelane'),
('Middelburg', 'Middelburg'),('Morgenzon', 'Morgenzon'),('Muden', 'Muden'),('Nelspruit', 'Nelspruit'),('Ogies', 'Ogies'),('Ohrigstad', 'Ohrigstad'),
('Perdekop', 'Perdekop'),('Piet Retief', 'Piet Retief'),('Pilgrims Rest', 'Pilgrims Rest'),('Sabie', 'Sabie'),('Secunda', 'Secunda'),
('Standerton', 'Standerton'),('Trichardt', 'Trichardt'),('Vaalbank', 'Vaalbank'),('Volksrust', 'Volksrust'),('Wakkerstroom', 'Wakkerstroom'),
('Waterval Boven', 'Waterval Boven'),('Waterval Onder', 'Waterval Onder'),('White River', 'White River'),('Witbank', 'Witbank')])
    kwazulunatal = SelectField(u'Area', choices=[('Ahrens', 'Ahrens'),('Aldinville', 'Aldinville'),('Alpha', 'Alpha'),
('Amanzimtoti', 'Amanzimtoti'),('Anerley', 'Anerley'),('Babanango', 'Babanango'),('Balgowan', 'Balgowan'),('Ballengeich', 'Ballengeich'),
('Ballito', 'Ballito'),('Banana Beach', 'Banana Beach'),('Bayala', 'Bayala'),('Bazley', 'Bazley'),('Bendigo', 'Bendigo'),
('Bergville', 'Bergville'),('Besters', 'Besters'),('Biggarsberg', 'Biggarsberg'),('Boston', 'Boston'),('Bulwer', 'Bulwer'),
('Calvert', 'Calvert'),('Camperdown', 'Camperdown'),('Candover', 'Candover'),('Cape Vidal', 'Cape Vidal'),('Catalina Bay', 'Catalina Bay'),
('Cato Ridge', 'Cato Ridge'),('Cedarville', 'Cedarville'),('Charlestown', 'Charlestown'),('Clansthal', 'Clansthal'),
('Clermont', 'Clermont'),('Colenso', 'Colenso'),('Dannhauser', 'Dannhauser'),('Darnall', 'Darnall'),('Doonside', 'Doonside'),
('Drummond', 'Drummond'),('Dundee', 'Dundee'),('Durban', 'Durban'),('ekuPhakameni', 'ekuPhakameni'),('Elandslaagte', 'Elandslaagte'),('Empangeni', 'Empangeni'),
('Eshowe', 'Eshowe'),('Estcourt', 'Estcourt'),('Franklin', 'Franklin'),('Glencoe', 'Glencoe'),('Greytown', 'Greytown'),('Hattingspruit', 'Hattingspruit'),
('Hibberdene', 'Hibberdene'),('Hillcrest', 'Hillcrest'),('Hilton', 'Hilton'),('Himeville', 'Himeville'),('Hluhluwe', 'Hluhluwe'),
('Howick', 'Howick'),('Ifafa Beach', 'Ifafa Beach'),('Illovo Beach', 'Illovo Beach'),('Impendle', 'Impendle'),
('Inanda', 'Inanda'),('Ingwavuma', 'Ingwavuma'),('Isipingo', 'Isipingo'),('Ixopo', 'Ixopo'),('Karridene', 'Karridene'),
('Kingsburgh', 'Kingsburgh'),('Kloof', 'Kloof'),('Kokstad', 'Kokstad'),('KwaDukuza', 'KwaDukuza'),('KwaMashu', 'KwaMashu'),('Ladysmith', 'Ladysmith'),
('La Lucia', 'La Lucia'),('La Mercy', 'La Mercy'),('Louwsburg', 'Louwsburg'),('Magabeni', 'Magabeni'),('Mahlabatini', 'Mahlabatini'),
('Margate', 'Margate'),('Melmoth', 'Melmoth'),('Merrivale', 'Merrivale'),('Mkuze', 'Mkuze'),('Mooirivier', 'Mooirivier'),('Mount Edgecombe', 'Mount Edgecombe'),
('Mtubatuba', 'Mtubatuba'),('Mtunzini', 'Mtunzini'),('Newcastle', 'Newcastle'),('New Germany', 'New Germany'),('New Hanover', 'New Hanover'),
('Nongoma', 'Nongoma'),('Nottingham Road', 'Nottingham Road'),('Palm Beach', 'Palm Beach'),('Park Rynie', 'Park Rynie'),('Paulpietersburg', 'Paulpietersburg'),
('Pennington', 'Pennington'),('Pietermaritzburg', 'Pietermaritzburg'),('Pinetown', 'Pinetown'),('Pomeroy', 'Pomeroy'),('Pongola', 'Pongola'),
('Port Edward', 'Port Edward'),('Port Shepstone', 'Port Shepstone'),('Queensburgh', 'Queensburgh'),('Ramsgate', 'Ramsgate'),
('Richards Bay', 'Richards Bay'),('Salt Rock', 'Salt Rock'),('Scottburgh', 'Scottburgh'),('Sezela', 'Sezela'),('Shelly Beach', 'Shelly Beach'),
('Southbroom', 'Southbroom'),('St Lucia', 'St Lucia'),('St Michaels-on-sea', 'St Michaels-on-sea'),('Tongaat', 'Tongaat'),
('Tugela Ferry', 'Tugela Ferry'),('Ubombo', 'Ubombo'),('Ulundi', 'Ulundi'),('Umbogintwini', 'Umbogintwini'),('Umdloti', 'Umdloti'),
('Umgababa', 'Umgababa'),('Umhlanga Rocks', 'Umhlanga Rocks'),('Umkomaas', 'Umkomaas'),('Umlazi', 'Umlazi'),('Umtentweni', 'Umtentweni'),
('Umzinto', 'Umzinto'),('Umzumbe', 'Umzumbe'),('Underberg', 'Underberg'),('Utrecht', 'Utrecht'),('Uvongo', 'Uvongo'),('Van Reenen', 'Van Reenen'),
('Verulam', 'Verulam'),('Virginia', 'Virginia'),('Vryheid', 'Vryheid'),('Warner Beach', 'Warner Beach'),('Wartburg', 'Wartburg'),
('Wasbank', 'Wasbank'),('Weenen', 'Weenen'),('Westville', 'Westville'),('Winkelspruit', 'Winkelspruit'),('Winterton', 'Winterton'),('York', 'York')])
    freestate = SelectField(u'Area', choices=[('Aberfeldy', 'Aberfeldy'),('Allandale', 'Allandale'),('Allanridge', 'Allanridge'),
('Allep', 'Allep'),('Arlington', 'Arlington'),('Bethlehem', 'Bethlehem'),('Bethulie', 'Bethulie'),('Bloemfontein', 'Bloemfontein'),
('Boshof', 'Boshof'),('Bothaville', 'Bothaville'),('Botshabelo', 'Botshabelo'),('Brandfort', 'Brandfort'),('Bultfontein', 'Bultfontein'),
('Boompie Alleen', 'Boompie Alleen'),('Clarens', 'Clarens'),('Clocolan', 'Clocolan'),('Cornelia', 'Cornelia'),('Dealesville', 'Dealesville'),
('Deneysville', 'Deneysville'),('Dewetsdorp', 'Dewetsdorp'),('Edenburg', 'Edenburg'),('Edenville', 'Edenville'),('Excelsior', 'Excelsior'),
('Fauresmith', 'Fauresmith'),('Ficksburg', 'Ficksburg'),('Fouriesburg', 'Fouriesburg'),('Frankfort', 'Frankfort'),('Harrismith', 'Harrismith'),
('Heilbron', 'Heilbron'),('Hennenman', 'Hennenman'),('Hertzogville', 'Hertzogville'),('Hobhouse', 'Hobhouse'),('Hoopstad', 'Hoopstad'),
('Jacobsdal', 'Jacobsdal'),('Jagersfontein', 'Jagersfontein'),('Kestell', 'Kestell'),('Kgotsong', 'Kgotsong'),('Koffiefontein', 'Koffiefontein'),
('Koppies', 'Koppies'),('Kroonstad', 'Kroonstad'),('Ladybrand', 'Ladybrand'),('Lindley', 'Lindley'),('Luckhoff', 'Luckhoff'),
('Makeleketla', 'Makeleketla'),('Marquard', 'Marquard'),('Memel', 'Memel'),('Odendaalsrus', 'Odendaalsrus'),('Oranjeville', 'Oranjeville'),
('Parys', 'Parys'),('Paul Roux', 'Paul Roux'),('Petrusburg', 'Petrusburg'),('Petrus Steyn', 'Petrus Steyn'),('Philippolis', 'Philippolis'),
('Phuthaditjhaba', 'Phuthaditjhaba'),('Reddersburg', 'Reddersburg'),('Reitz', 'Reitz'),('Rosendal', 'Rosendal'),('Rouxville', 'Rouxville'),
('Sasolburg', 'Sasolburg'),('Senekal', 'Senekal'),('Smithfield', 'Smithfield'),('Springfontein', 'Springfontein'),('Steynsrus', 'Steynsrus'),
('Swinburne', 'Swinburne'),('Thaba Nchu', 'Thaba Nchu'),('Theunissen', 'Theunissen'),('Trompsburg', 'Trompsburg'),('Tweeling', 'Tweeling'),
('Tweespruit', 'Tweespruit'),('Van Stadensrus', 'Van Stadensrus'),('Ventersburg', 'Ventersburg'),('Verkeerdevlei', 'Verkeerdevlei'),
('Viljoenskroon', 'Viljoenskroon'),('Villiers', 'Villiers'),('Vrede', 'Vrede'),('Vredefort', 'Vredefort'),('Warden', 'Warden'),
('Welkom', 'Welkom'),('Wepener', 'Wepener'),('Wesselsbron', 'Wesselsbron'),('Winburg', 'Winburg'),('Zastron', 'Zastron')])
    westerncape = SelectField(u'Area', choices=[('Aan de Doorns', 'Aan de Doorns'),('Abbotsdale', 'Abbotsdale'),('Agulhas', 'Agulhas'),
('Albertinia', 'Albertinia'),('Amalienstein', 'Amalienstein'),('Arniston', 'Arniston'),('Ashton', 'Ashton'),('Atlantis', 'Atlantis'),
('Aurora', 'Aurora'),('Baardskeerdersbos', 'Baardskeerdersbos'),('Barrington', 'Barrington'),('Barrydale', 'Barrydale'),
('Baviaan', 'Baviaan'),('Beaufort West', 'Beaufort West'),('Bellville', 'Bellville'),('Berea', 'Berea'),('Bergplaas', 'Bergplaas'),
('Bergrivier', 'Bergrivier'),('Biesiesfontein', 'Biesiesfontein'),('Bitterfontein', 'Bitterfontein'),('Bonnievale', 'Bonnievale'),
('Bredasdorp', 'Bredasdorp'),('Buffelsjagbaai', 'Buffelsjagbaai'),('Caledon', 'Caledon'),('Calitzdorp', 'Calitzdorp'),
('Camps Bay', 'Camps Bay'),('Cape Town', 'Cape Town'),('Ceres', 'Ceres'),('Churchaven', 'Churchaven'),('Citrusdal', 'Citrusdal'),
('Clanwilliam', 'Clanwilliam'),('Claremont', 'Claremont'),('Clarkson', 'Clarkson'),('Clifton', 'Clifton'),('Constantia', 'Constantia'),
('Darling', 'Darling'),('De Doorns', 'De Doorns'),('De Kelders', 'De Kelders'),('De Rust', 'De Rust'),('Doringbaai', 'Doringbaai'),
('Dysselsdorp', 'Dysselsdorp'),('Eendekuil', 'Eendekuil'),('Elandsbaai', 'Elandsbaai'),('Elim', 'Elim'),('Elgin', 'Elgin'),
('Fisherhaven', 'Fisherhaven'),('Franskraal', 'Franskraal'),('Franschhoek', 'Franschhoek'),('Gansbaai', 'Gansbaai'),('Genadendal', 'Genadendal'),
('George', 'George'),('Gouda', 'Gouda'),('Graafwater', 'Graafwater'),('Grabouw', 'Grabouw'),('Greyton', 'Greyton'),('Heidelberg', 'Heidelberg'),
('Hermanus', 'Hermanus'),('Hopefield', 'Hopefield'),('Keurboomstrand', 'Keurboomstrand'),('Khayelitsha', 'Khayelitsha'),('Knysna', 'Knysna'),
('Laingsburg', 'Laingsburg'),('Lamberts Bay', 'Lamberts Bay'),('Matjiesfontein', 'Matjiesfontein'),('Mossel Bay', 'Mossel Bay'),('Oudtshoorn', 'Oudtshoorn'),
('Paarl', 'Paarl'),('Piketberg', 'Piketberg'),('Plettenberg Bay', 'Plettenberg Bay'),('Pniel', 'Pniel'),('Prins Albert', 'Prins Albert'),
('Riebeek Kasteel', 'Riebeek Kasteel'),('Somerset West', 'Somerset West'),('Stellenbosch', 'Stellenbosch'),('Strand', 'Strand'),
('Swartberg', 'Swartberg'),('Swellendam', 'Swellendam'),('Tulbagh', 'Tulbagh'),('Uniondale', 'Uniondale'),('Wellington', 'Wellington'),
('Wilderness', 'Wilderness'),('Worcester', 'Worcester')])
    easterncape = SelectField(u'Area', choices=[('Aberdeen', 'Aberdeen'),('Adelaide', 'Adelaide'),('Adendorp', 'Adendorp'),
('Addo', 'Addo'),('Alderley', 'Alderley'),('Alexandria', 'Alexandria'),('Alice', 'Alice'),('Alicedale', 'Alicedale'),
('Aliwal North', 'Aliwal North'),('Bailey', 'Bailey'),('Balfour', 'Balfour'),('Barakke', 'Barakke'),('Barkly East', 'Barkly East'),
('Baroda', 'Baroda'),('Baroe', 'Baroe'),('Bathurst', 'Bathurst'),('Bedford', 'Bedford'),('Behulpsaam', 'Behulpsaam'),
('Bell', 'Bell'),('Bellevue', 'Bellevue'),('Berlin', 'Berlin'),('Bethelsdorp', 'Bethelsdorp'),('Bhisho', 'Bhisho'),
('Bityi', 'Bityi'),('Bonza Bay', 'Bonza Bay'),('Braunschweig', 'Braunschweig'),('Burgersdorp', 'Burgersdorp'),
('Butterworth', 'Butterworth'),('Cala', 'Cala'),('Cambria', 'Cambria'),('Cannon Rocks', 'Cannon Rocks'),('Cape St. Francis', 'Cape St. Francis'),
('Cathcart', 'Cathcart'),('Chalumna', 'Chalumna'),('Chintsa', 'Chintsa'),('Clarkebury', 'Clarkebury'),('Clifford', 'Clifford'),
('Coega', 'Coega'),('Coffee Bay', 'Coffee Bay'),('Cofimvaba', 'Cofimvaba'),('Coghlan', 'Coghlan'),('Colchester', 'Colchester'),
('Coleford', 'Coleford'),('Cookhouse', 'Cookhouse'),('Cradock', 'Cradock'),('Despatch', 'Despatch'),('Dohne', 'Dohne'),
('Dordrecht', 'Dordrecht'),('Dutywa', 'Dutywa'),('East London', 'East London'),('Elliot', 'Elliot'),('Flagstaff', 'Flagstaff'),
('Fort Beaufort', 'Fort Beaufort'),('Gcuwa', 'Gcuwa'),('Gonubie', 'Gonubie'),('Graaff-Reinet', 'Graaff-Reinet'),
('Grahamstown', 'Grahamstown'),('Hankey', 'Hankey'),('Hofmeyr', 'Hofmeyr'),('Humansdorp', 'Humansdorp'),('Jansenville', 'Jansenville'),
('Jeffreys Bay', 'Jeffreys Bay'),('Kenton-on-Sea', 'Kenton-on-Sea'),('King Williams Town', 'King Williams Town'),('Kirkwood', 'Kirkwood'),
('Lady Frere', 'Lady Frere'),('Lady Grey', 'Lady Grey'),('Maclear', 'Maclear'),('Madadeni', 'Madadeni'),('Mandini', 'Mandini'),
('Matatiele', 'Matatiele'),('Middelburg', 'Middelburg'),('Molteno', 'Molteno'),('Mount Fletcher', 'Mount Fletcher'),('Mthatha', 'Mthatha'),
('Engcobo', 'Engcobo'),('Nieu-Bethesda', 'Nieu-Bethesda'),('Oyster Bay', 'Oyster Bay'),('Patensie', 'Patensie'),('Paterson', 'Paterson'),
('Port Alfred', 'Port Alfred'),('Port Elizabeth', 'Port Elizabeth'),('Queenstown', 'Queenstown'),('Somerset East', 'Somerset East'),
('Steynsburg', 'Steynsburg'),('St Francis Bay', 'St Francis Bay'),('Stutterheim', 'Stutterheim'),('Tarkastad', 'Tarkastad'),
('Uitenhage', 'Uitenhage'),('uMthatha', 'uMthatha'),('Whittlesea', 'Whittlesea'),('Zwelitsha', 'Zwelitsha')])
    northerncape = SelectField(u'Area', choices=[('Aalwynsfontein', 'Aalwynsfontein'),
('Aggeneys', 'Aggeneys'),('Alexander Bay', 'Alexander Bay'),('Andriesvale', 'Andriesvale'),('Askham', 'Askham'),
('Augrabies', 'Augrabies'),('Barkly West', 'Barkly West'),('Bekker', 'Bekker'),('Belmont', 'Belmont'),
('Bermolli', 'Bermolli'),('Biesiespoort', 'Biesiespoort'),('Britstown', 'Britstown'),('Calvinia', 'Calvinia'),
('Campbell', 'Campbell'),('Carlton', 'Carlton'),('Carnarvon', 'Carnarvon'),('Carolusberg', 'Carolusberg'),
('Concordia', 'Concordia'),('Colesberg', 'Colesberg'),('Colston', 'Colston'),('Copperton', 'Copperton'),
('Danielskuil', 'Danielskuil'),('De Aar', 'De Aar'),('Delportshoop', 'Delportshoop'),('Dibeng', 'Dibeng'),
('Dingleton', 'Dingleton'),('Douglas', 'Douglas'),('Fraserburg', 'Fraserburg'),('Griekwastad', 'Griekwastad'),
('Groblershoop', 'Groblershoop'),('Hopetown', 'Hopetown'),('Kimberley', 'Kimberley'),('Modder River', 'Modder River'),
('Orania', 'Orania'),('Prieska', 'Prieska'),('Richmond', 'Richmond'),('Springbok', 'Springbok'),('Strydenburg', 'Strydenburg'),
('Upington', 'Upington'),('Victoria West', 'Victoria West'),('Warrenton', 'Warrenton'),
('Williston', 'Williston')])
    northwest = SelectField(u'Area', choices=[('Albertshoek', 'Albertshoek'),
('Alettasrus', 'Alettasrus'),('Amalia', 'Amalia'),('Babelegi', 'Babelegi'),('Bakerville', 'Bakerville'),('Barberspan', 'Barberspan'),
('Beestekraal', 'Beestekraal'),('Bethanie', 'Bethanie'),('Bewley', 'Bewley'),('Biesiesvlei', 'Biesiesvlei'),
('Bloemhof', 'Bloemhof'),('Bray', 'Bray'),('Brits', 'Brits'),('Broederstroom', 'Broederstroom'),('Carlsonia', 'Carlsonia'),
('Christiana', 'Christiana'),('Coligny', 'Coligny'),('Delareyville', 'Delareyville'),('Derby', 'Derby'),
('Ganyesa', 'Ganyesa'),('Ga-Rankuwa', 'Ga-Rankuwa'),('Groot Marico', 'Groot Marico'),('Lichtenburg', 'Lichtenburg'),
('Mafikeng', 'Mafikeng'),('Orkney', 'Orkney'),('Potchefstroom', 'Potchefstroom'),('Rustenburg', 'Rustenburg'),
('Vryburg', 'Vryburg'),('Wolmaransstad', 'Wolmaransstad'),('Zeerust', 'Zeerust')])
    gauteng = SelectField(u'Area', choices=[('Akasia', 'Akasia'),
('Alberton', 'Alberton'),('Alexandra', 'Alexandra'),('Atteridgeville', 'Atteridgeville'),('Ban ', 'Ban '),
('Bapsfontein', 'Bapsfontein'),('Benoni', 'Benoni'),('Boipatong', 'Boipatong'),('Boksburg', 'Boksburg'),
('Bophelong', 'Bophelong'),('Brakpan', 'Brakpan'),('Bronkhorstspruit', 'Bronkhorstspruit'),
('Carletonville', 'Carletonville'),('Centurion', 'Centurion'),('Chantelle', 'Chantelle'),('Cullinan', 'Cullinan'),
('Daveyton', 'Daveyton'),('Devon', 'Devon'),('Duduza', 'Duduza'),('Edenvale', 'Edenvale'),('Evaton', 'Evaton'),
('Fochville', 'Fochville'),('Germiston', 'Germiston'),('Hammanskraal', 'Hammanskraal'),('Heidelberg', 'Heidelberg'),
('Henley on Klip', 'Henley on Klip'),('Irene', 'Irene'),('Isando', 'Isando'),('Johannesburg', 'Johannesburg'),
('Katlehong', 'Katlehong'),('Kempton Park', 'Kempton Park'),('Kromdraai', 'Kromdraai'),('Krugersdorp', 'Krugersdorp'),
('KwaThema', 'KwaThema'),('Lenasia', 'Lenasia'),('Lyttelton', 'Lyttelton'),('Magaliesburg', 'Magaliesburg'),
('Mamelodi', 'Mamelodi'),('Meyerton', 'Meyerton'),('Midrand', 'Midrand'),('Muldersdrift', 'Muldersdrift'),
('Nigel', 'Nigel'),('Orchards', 'Orchards'),('Pretoria', 'Pretoria'),('Randburg', 'Randburg'),('Randfontein', 'Randfontein'),
('Ratanda', 'Ratanda'),('Roodepoort', 'Roodepoort'),('Rooihuiskraal', 'Rooihuiskraal'),('Sandton', 'Sandton'),
('Sebokeng', 'Sebokeng'),('Sharpeville', 'Sharpeville'),('Soshanguve', 'Soshanguve'),('Soweto', 'Soweto'),('Springs', 'Springs'),
('Tembisa', 'Tembisa'),('Thokoza', 'Thokoza'),('Tsakane', 'Tsakane'),('Vanderbijlpark', 'Vanderbijlpark'),('Vereeniging', 'Vereeniging'),
('Vosloorus', 'Vosloorus'),('Wedela', 'Wedela'),('Westonaria', 'Westonaria')])
    limpopo = SelectField(u'Area', choices=[('Afguns', 'Afguns'),('Alldays', 'Alldays'),('Baltimore', 'Baltimore'),
('Bandelierkop', 'Bandelierkop'),('Bandur', 'Bandur'),('Beauty', 'Beauty'),('Beitbridge', 'Beitbridge'),('Bela-Bela', 'Bela-Bela'),
('Burgersfort', 'Burgersfort'),('Carlow', 'Carlow'),('Chuniespoort', 'Chuniespoort'),('Duiwelskloof', 'Duiwelskloof'),
('Giyani', 'Giyani'),('Gravelotte ', 'Gravelotte '),('Groblersdal', 'Groblersdal'),('Haenertsburg', 'Haenertsburg'),
('Hoedspruit', 'Hoedspruit'),('Lephalale', 'Lephalale'),('Louis Trichardt', 'Louis Trichardt'),('Marble Hall', 'Marble Hall'),
('Modimolle', 'Modimolle'),('Mokopane', 'Mokopane'),('Musina', 'Musina'),('Naboomspruit', 'Naboomspruit'),('Phalaborwa', 'Phalaborwa'),
('Polokwane', 'Polokwane'),('Shawela', 'Shawela'),('Thabazimbi', 'Thabazimbi'),('Thohoyandou', 'Thohoyandou'),('Vaalwater', 'Vaalwater'),
('Vivo', 'Vivo')])
